apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: default
data:
  APP_ENV: "local"
  APP_NAME: "hello-app"
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: "supersecret123"
